### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by Aqa-Ib** [funilrys/aur-cava#15] opened 2024-05-13 13:49 UTC
AUR "cava" package does not build. However "cava-git" package does build fine.

[cava.log](https://github.com/funilrys/aur-cava/files/15295395/cava.log)

Thanks.

**Comment by funilrys** [comment] 2024-05-13 17:14
Interesting, I can't reproduce this ... Is that on a fresh install ?

**Comment by funilrys** [comment] 2024-05-13 17:38
*Correction: I can reproduce it.

**Comment by funilrys** [comment] 2024-05-14 21:54
Should be fixed by latest release.

**Closed as completed by funilrys** 2024-05-14 21:54 UTC

**Comment by Aqa-Ib** [comment] 2024-05-14 22:44
Thank you very much. I wish you the best.
